# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 20:57
import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),

        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_type', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('online_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('objectid', models.IntegerField(null=True, unique=True)),
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(max_length=250, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(7, 'Parc'), (8, 'Municipalité'), (9, 'Mont'), (10, 'Région touristique'), (11, 'Réseau')], null=True)),
                ('parking', models.IntegerField(blank=True, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('dog_allowed', models.BooleanField()),
                ('living_rules', models.TextField(blank=True, null=True)),
                ('fare_note', models.TextField(blank=True, null=True)),
                ('transport', models.TextField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('network_length', models.FloatField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Address')),
                ('contact', models.ManyToManyField(blank=True, to='utils.Contact')),
                ('images', models.ManyToManyField(blank=True, to='utils.Image')),
            ],
            managers=[
                ('objects_with_eager_loading', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('objectid', models.IntegerField(null=True, unique=True)),
                ('poi_id', models.AutoField(primary_key=True, serialize=False)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('premium', models.BooleanField(default=False)),
                ('fare', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=250, null=True)),
                ('position_quality', models.IntegerField(default=0)),
                ('visible_in_map', models.IntegerField(default=0)),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Hébergement'), (2, "Retiré (poste d'accueil)"), (3, 'Stationnement'), (4, 'Activité'), (5, 'Restaurant'), (6, 'Autre')], null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Address')),
                ('contact', models.ManyToManyField(blank=True, to='utils.Contact')),
                ('images', models.ManyToManyField(blank=True, to='utils.Image')),
                ('location', models.ManyToManyField(blank=True, to='location.Location')),
            ],
            managers=[
                ('objects_with_eager_loading', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Address')),
                ('locations', models.ManyToManyField(to='location.Location')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_of_interests', to='location.PointOfInterestType'),
        ),
        migrations.AddField(
            model_name='fare',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='location.Location'),
        ),
    ]
