# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 15:26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='fare',
            field=models.TextField(blank=True, null=True),
        ),
    ]
