# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 17:08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20161021_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='objectid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='objectid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
