# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 20:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_locationcopy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationCopy',
            new_name='LocationLimbo',
        ),
    ]
