# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 21:43
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20161201_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationlimbo',
            name='original',
        ),
    ]
