# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 22:12
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_remove_locationlimbo_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlimbo',
            name='original',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
