# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 17:36
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_locationlimbo_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='locationlimbo',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
