# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 14:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_auto_20161220_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='location',
        ),
        migrations.DeleteModel(
            name='Fare',
        ),
    ]
