# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_auto_20170216_1523'),
    ]
