# Generated by Django 2.0.4 on 2018-05-01 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_auto_20170220_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Address'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Address'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_of_interests', to='location.PointOfInterestType'),
        ),
        migrations.AlterField(
            model_name='transportservice',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.Address'),
        ),
        migrations.AlterField(
            model_name='transportservice',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.Contact'),
        ),
    ]
