# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-31 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Location = apps.get_model('location', 'Location')
    for location in Location.objects_with_eager_loading.all():
        location.search_uuid = uuid.uuid4()
        location.save(update_fields=['search_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_auto_20170220_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='search_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='location',
            name='search_uuid',
            field=models.UUIDField(unique=True, editable=False)
        )
    ]
