# Generated by Django 2.0.4 on 2018-07-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_auto_20180501_0048'),
        ('location', '0020_location_search_uuid'),
    ]

    operations = [
    ]
