# Generated by Django 2.0.4 on 2018-08-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_auto_20180724_1556'),
        ('location', '0021_merge_20180721_0109'),
    ]

    operations = [
    ]
