# Generated by Django 2.0.4 on 2018-08-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_merge_20180812_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportservice',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Address'),
        ),
        migrations.AlterField(
            model_name='transportservice',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Contact'),
        ),
    ]
