# Generated by Django 2.0.4 on 2018-09-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_auto_20180812_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Polygon_of_interests', to='location.PointOfInterestType'),
        ),
    ]
