# Generated by Django 2.0.4 on 2018-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_auto_20180903_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.IntegerField(blank=True, choices=[(8, 'Municipalité'), (9, 'Mont'), (10, 'Région touristique'), (11, 'Réseau')], null=True),
        ),
    ]
