# Generated by Django 2.0.4 on 2018-11-23 01:39

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0026_remove_location_search_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=20)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(max_length=300, upload_to='images/')),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointOfInterestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=20)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(max_length=300, upload_to='images/')),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.PointOfInterest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
