# Generated by Django 2.0.4 on 2018-11-27 00:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0027_locationimage_pointofinterestimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='images',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='images',
        ),
    ]
