# Generated by Django 2.0.4 on 2018-11-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0028_auto_20181127_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='location.Location'),
        ),
        migrations.AlterField(
            model_name='pointofinterestimage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='location.PointOfInterest'),
        ),
    ]
