# Generated by Django 2.0.4 on 2018-11-28 23:58

from django.db import migrations
import django.db.models.manager
import easy_thumbnails.fields
import hikster.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0029_auto_20181127_0033'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('objects_with_eager_loading', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pointofinterest',
            managers=[
                ('objects_with_eager_loading', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=300, upload_to=hikster.utils.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='pointofinterestimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=300, upload_to=hikster.utils.models.get_image_upload_to),
        ),
    ]
