# Generated by Django 2.0.4 on 2018-12-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('location', '0031_auto_20181206_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportservice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transportservice',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='transportservice',
            name='phone',
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organization'),
        ),
        migrations.DeleteModel(
            name='TransportService',
        ),
    ]
