# Generated by Django 2.1.5 on 2019-02-26 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0032_auto_20181229_2201'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('objects_with_eager_loading', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pointofinterest',
            managers=[
                ('objects_with_eager_loading', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='organizations.Organization'),
        ),
    ]
