# Generated by Django 2.1.5 on 2019-03-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0033_auto_20190226_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
