# Generated by Django 2.1.5 on 2019-04-17 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0034_location_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 4, 17, 9, 4, 48, 101350, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
