# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 20:57
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager

from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),

        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('objectid', models.IntegerField(null=True, unique=True)),
                ('trail_id', models.AutoField(primary_key=True, serialize=False)),
                ('trail_type', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Débutant'), (2, 'Modéré'), (3, 'Intermédiaire'), (4, 'Soutenu'), (5, 'Exigeant')], null=True)),
                ('total_length', models.FloatField(blank=True, null=True)),
                ('path_type', models.IntegerField(blank=True, choices=[(0, 'Non determine'), (1, 'Aller simple'), (2, 'Boucle'), (3, 'Aller-retour')], null=True)),
                ('height_positive', models.IntegerField(blank=True, null=True)),
                ('height_negative', models.IntegerField(blank=True, null=True)),
                ('height_difference', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('owner_url', models.URLField(blank=True, null=True)),
                ('hikster_creation', models.IntegerField(blank=True, null=True)),
                ('parking', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326)),
                ('exploitation_period', models.ManyToManyField(blank=True, to='utils.ExploitationPeriod')),
                ('images', models.ManyToManyField(blank=True, to='utils.Image')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='location.Location')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            managers=[
                ('objects_with_eager_loading', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TrailSection',
            fields=[
                ('objectid', models.IntegerField(unique=True)),
                ('trail_id', models.AutoField(primary_key=True, serialize=False)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(dim=3, null=True, srid=4326)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Débutant'), (2, 'Modéré'), (3, 'Intermédiaire'), (4, 'Soutenu'), (5, 'Exigeant')], null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('hikster_creation', models.IntegerField(blank=True, null=True)),
                ('in_trail', models.IntegerField(default=0)),
                ('activity', models.ManyToManyField(to='hike.Activity')),
            ],
            managers=[
                ('objects_with_eager_loading', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TrailStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_steps', to='hike.Trail')),
                ('trail_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_steps', to='hike.TrailSection')),
            ],
        ),
        migrations.AddField(
            model_name='trail',
            name='trail_sections',
            field=models.ManyToManyField(blank=True, to='hike.TrailSection'),
        ),
        migrations.AlterUniqueTogether(
            name='trailstep',
            unique_together=set([('trail_section', 'trail', 'step')]),
        ),
    ]
