# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 20:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('hike', '0001_initial'),
    ]
