# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 16:48
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0002_trail_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hike.Activity'),
        ),
    ]
