# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 13:35
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0003_trail_activity'),
    ]
