# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 21:32
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0004_trailsection_activities'),
    ]
