# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 20:35
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0005_trail_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='parking',
        ),
    ]
