# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 17:45
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_merge_20161201_1437'),
        ('location', '0012_auto_20161202_1736'),
        ('hike', '0007_trail_exploitation_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailLimbo',
            fields=[
                ('objectid', models.IntegerField(null=True, unique=True)),
                ('trail_id', models.AutoField(primary_key=True, serialize=False)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326)),
                ('trail_type', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Débutant'), (2, 'Modéré'), (3, 'Intermédiaire'), (4, 'Soutenu'), (5, 'Exigeant')], null=True)),
                ('total_length', models.FloatField(blank=True, null=True)),
                ('path_type', models.IntegerField(blank=True, choices=[(0, 'Non determine'), (1, 'Aller simple'), (2, 'Boucle'), (3, 'Aller-retour')], null=True)),
                ('height_positive', models.IntegerField(blank=True, null=True)),
                ('height_negative', models.IntegerField(blank=True, null=True)),
                ('height_difference', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
                ('hikster_creation', models.IntegerField(blank=True, null=True)),
                ('parking', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('exploitation_periods', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hike.Activity')),
                ('images', models.ManyToManyField(blank=True, to='utils.Image')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_copy', to='location.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='trail',
            name='color',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='owner_url',
        ),
        migrations.AddField(
            model_name='traillimbo',
            name='original',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hike.Trail'),
        ),
        migrations.AddField(
            model_name='traillimbo',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
        migrations.AddField(
            model_name='traillimbo',
            name='trail_sections',
            field=models.ManyToManyField(blank=True, to='hike.TrailSection'),
        ),
    ]
