# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 19:56
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0008_auto_20161205_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traillimbo',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='traillimbo',
            name='images',
        ),
        migrations.RemoveField(
            model_name='traillimbo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='traillimbo',
            name='original',
        ),
        migrations.RemoveField(
            model_name='traillimbo',
            name='region',
        ),
        migrations.RemoveField(
            model_name='traillimbo',
            name='trail_sections',
        ),
        migrations.DeleteModel(
            name='TrailLimbo',
        ),
    ]
