# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 21:26
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0006_auto_20161214_2035'),
        ('hike', '0008_auto_20161205_1745'),
    ]

    operations = [
    ]
