# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 16:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0009_auto_20161220_1956'),
        ('hike', '0009_merge_20161214_2126'),
    ]

    operations = [
    ]
