# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 20:46
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0012_auto_20170112_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='activity',
            new_name='activities',
        ),
    ]
