# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 22:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0013_auto_20170112_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='exploitation_periods',
            new_name='opening_dates',
        ),
    ]
