# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 19:40
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0014_auto_20170112_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(0, 'Indéterminé'), (1, 'Randonnée'), (2, 'Raquette')], null=True),
        ),
    ]
