# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0017_trail_slug'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='trail',
        #     name='objectid',
        #     field=models.IntegerField(),
        # ),
    ]
