# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0018_auto_20170220_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='objectid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
