# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 19:41
from __future__ import unicode_literals

from celery.loaders import default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0020_auto_20170307_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ascent_pace',
            field=models.IntegerField(null=True, default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='descent_pace',
            field=models.IntegerField(null=True, default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='flat_pace',
            field=models.IntegerField(null=True, default=1),
        ),
    ]
