# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-27 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0021_auto_20180320_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ascent_pace',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='descent_pace',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='flat_pace',
            field=models.IntegerField(null=True),
        ),
    ]
