# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 14:40
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0021_auto_20170711_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtrailsection',
            name='evnt',
            field=models.ForeignKey(db_column='evnt', on_delete=django.db.models.deletion.CASCADE, to='hike.Event'),
        ),
        migrations.AlterField(
            model_name='eventtrailsection',
            name='trailsection',
            field=models.ForeignKey(db_column='trailsection', on_delete=django.db.models.deletion.DO_NOTHING, to='hike.TrailSection'),
        ),
    ]
