# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0021_auto_20180320_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='dev1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='dev2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='dev3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='dev4',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ascent_pace',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='descent_pace',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='flat_pace',
            field=models.IntegerField(default=1),
        ),
    ]
