# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-27 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0022_auto_20180322_1540'),
        ('hike', '0022_auto_20180327_2046'),
    ]

    operations = [
    ]
