# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 15:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0022_auto_20170711_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='arrival',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='departure',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
