# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 17:36
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0023_auto_20170711_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ascent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='descent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lgth',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_elevation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_elevation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slope',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='ascent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='descent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='lgth',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='max_elevation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='min_elevation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='slope',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
