# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 20:51
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0024_auto_20170724_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailsection',
            name='in_trail',
        ),
        migrations.AlterField(
            model_name='trail',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(0, 'Indéterminé'), (1, 'Randonnée pédestre'), (2, 'Raquette'), (3, 'Randonnée hivernale'), (4, 'Vélo de montagne'), (5, 'Fatbike'), (6, 'Vélo'), (7, 'Ski de fond'), (8, 'Équitation')], default=0, null=True),
        ),
    ]
