# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 21:30
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0025_auto_20170817_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trailstep',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='trailstep',
            name='trail',
        ),
        migrations.RemoveField(
            model_name='trailstep',
            name='trail_section',
        ),
        migrations.DeleteModel(
            name='TrailStep',
        ),
    ]
