# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 13:53
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0027_auto_20170825_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailsection',
            name='activity',
            field=models.ManyToManyField(blank=True, to='hike.Activity'),
        ),
    ]
