# Generated by Django 2.0.4 on 2018-07-08 16:03

from django.db import migrations, models
import django.db.models.deletion
import os


def load_sql_statement_from_file(file_name):
    file_path = os.path.join(os.path.dirname(__file__), '../sql', file_name)
    sql_statement = open(file_path).read()
    return sql_statement


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0028_auto_20171004_1353'),
    ]

    operations = [
        migrations.RunSQL(load_sql_statement_from_file('10_utility.sql')),
        migrations.RunSQL(
            load_sql_statement_from_file('20_event_triggers.sql')),
        migrations.RunSQL(load_sql_statement_from_file(
            '30_hike_eventtrailsection_triggers.sql')),
        migrations.RunSQL(
            load_sql_statement_from_file('40_hike_trailsection_triggers.sql')),
        migrations.RunSQL(
            load_sql_statement_from_file('50_trailsection_merge.sql')),
        migrations.RunSQL(
            load_sql_statement_from_file('60_hike_trail_triggers.sql')),
        migrations.AlterField(
            model_name='trail',
            name='hikster_creation',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trails', to='location.Location'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Location'),
        ),
    ]
