# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0029_auto_20180328_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailsection',
            name='objectid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
