# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0030_auto_20180329_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailsectionActivities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trailsection_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
            ],
        ),
    ]
