# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-06 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0033_auto_20180406_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='trailsection_activities_uuid',
        ),
        migrations.AddField(
            model_name='trailsection',
            name='trailsection_activities_uuid',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
