# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-11 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0034_auto_20180406_2027'),
        ('hike', '0023_merge_20180327_2053'),
    ]

    operations = [
    ]
