# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-31 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Trail = apps.get_model('hike', 'Trail')
    for trail in Trail.objects_with_eager_loading.all():
        trail.search_uuid = uuid.uuid4()
        trail.save(update_fields=['search_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0035_merge_20180411_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='search_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trail',
            name='search_uuid',
            field=models.UUIDField(unique=True, editable=False)
        )
    ]
