# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-16 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0036_trail_search_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ascent_pace',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='descent_pace',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dev1',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dev2',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dev3',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dev4',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance1',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance2',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance3',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance4',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='flat_pace',
            field=models.FloatField(default=1),
        ),
    ]
