# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-24 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0037_auto_20180716_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='search_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
