# Generated by Django 2.0.4 on 2018-07-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0037_auto_20180716_1531'),
    ]

    operations = [
    ]
