# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0038_auto_20180724_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ascent_pace',
            field=models.FloatField(default=1, verbose_name='ascent pace (M)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='descent_pace',
            field=models.FloatField(default=1, verbose_name='descent pace (M)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dev1',
            field=models.FloatField(default=1, verbose_name='dev 1 (M)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dev2',
            field=models.FloatField(default=1, verbose_name='dev 2 (M)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dev3',
            field=models.FloatField(default=1, verbose_name='dev 3 (M)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dev4',
            field=models.FloatField(default=1, verbose_name='dev 4 (M)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance1',
            field=models.FloatField(default=1, verbose_name='distance 1 (KM)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance2',
            field=models.FloatField(default=1, verbose_name='distance 2 (KM)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance3',
            field=models.FloatField(default=1, verbose_name='distance 3 (KM)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance4',
            field=models.FloatField(default=1, verbose_name='distance 4 (KM)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='flat_pace',
            field=models.FloatField(default=1, verbose_name='flat pace (M)'),
        ),
    ]
