# Generated by Django 2.0.4 on 2018-08-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0040_auto_20180809_1743'),
        ('hike', '0038_merge_20180721_0109'),
    ]

    operations = [
    ]
