# Generated by Django 2.0.4 on 2018-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0041_merge_20180812_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='hikster_creation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
