# Generated by Django 2.0.4 on 2018-08-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0043_auto_20180823_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailsection',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='trailsection',
            name='difficulty',
        ),
    ]
