# Generated by Django 2.0.4 on 2018-08-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0044_auto_20180823_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='max_elevation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='min_elevation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
