# Generated by Django 2.0.4 on 2018-09-03 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0045_auto_20180823_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='shape_simplified',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
