# Generated by Django 2.0.4 on 2018-11-10 20:47

from django.db import migrations


def migrate_activities(apps, schema_editor):
    Trail = apps.get_model('hike', 'Trail')
    TrailActivity = apps.get_model('hike', 'TrailActivity')
    for trail in Trail.objects.all():
        for activity in trail.activities.all():
            ta = TrailActivity(
                trail=trail,
                activity=activity
            )
            ta.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0047_trailactivity'),
    ]

    operations = [
        migrations.RunPython(migrate_activities)
    ]
