# Generated by Django 2.0.4 on 2018-11-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0048_auto_20181110_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailactivity',
            options={'verbose_name_plural': 'trail activities'},
        ),
        migrations.AlterModelManagers(
            name='trail',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='trail',
            name='search_uuid',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='shape_simplified',
        ),
        migrations.AlterField(
            model_name='trailactivity',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration, in minutes', null=True),
        ),
    ]
