# Generated by Django 2.0.4 on 2018-11-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0050_remove_trail_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='hike.Activity'),
        ),
        migrations.AlterField(
            model_name='trailactivity',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hike.Trail'),
        ),
    ]
