# Generated by Django 2.0.4 on 2018-11-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0052_trailimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='images',
        ),
    ]
