# Generated by Django 2.0.4 on 2018-11-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0053_remove_trail_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailimage',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hike.Trail'),
        ),
    ]
