# Generated by Django 2.0.4 on 2018-12-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0055_auto_20181128_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailimage',
            name='old_image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
