# Generated by Django 2.1.5 on 2019-03-22 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0056_trailimage_old_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailSectionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_sections', to='hike.Activity')),
                ('trail_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hike.TrailSection')),
            ],
            options={
                'verbose_name': 'Trail Section Activities',
            },
        ),
        migrations.AlterUniqueTogether(
            name='trailsectionactivity',
            unique_together={('trail_section', 'activity')},
        ),
    ]
