# Generated by Django 2.1.5 on 2019-03-22 13:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0057_trailsectionactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailsection',
            name='shape',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='shape_2d',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
