# Generated by Django 2.1.5 on 2019-07-09 14:10

import os
from django.db import migrations


def load_sql_statement_from_file(file_name):
    file_path = os.path.join(os.path.dirname(__file__), '../sql', file_name)
    sql_statement = open(file_path).read()
    return sql_statement


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0063_auto_20190628_0744'),
    ]

    operations = [
        migrations.RunSQL(load_sql_statement_from_file('72_fix_duplicate_trailsection.sql')),
    ]
