# Generated by Django 2.1.5 on 2019-08-14 09:29

from django.db import migrations
import os

def load_sql_statement_from_file(file_name):
    file_path = os.path.join(os.path.dirname(__file__), '../sql', file_name)
    sql_statement = open(file_path).read()
    return sql_statement

class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0064_fix_duplicate_trailsection'),
    ]

    operations = [
        migrations.RunSQL(load_sql_statement_from_file('80_spatial_indexing.sql')),
    ]
