# Generated by Django 2.1.5 on 2019-09-06 07:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0065_auto_20190815_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='shape_2d',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, null=True, spatial_index=False, srid=4326),
        ),
        migrations.AlterField(
            model_name='trailsection',
            name='shape_2d',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, spatial_index=False, srid=4326),
        ),
    ]
