# Generated by Django 2.0.4 on 2018-12-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_delete_image'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
