# Generated by Django 2.1.5 on 2019-08-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_members_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLoads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loads', models.IntegerField(blank=True, null=True)),
                ('max_loads', models.IntegerField(default=1000000)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='aid',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='maploads',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_members', to='organizations.Organization'),
        ),
    ]
