# Generated by Django 2.1.5 on 2019-09-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20190830_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
