# Generated by Django 2.1.5 on 2019-09-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maploads',
            name='loads',
            field=models.IntegerField(default=0),
        ),
    ]
