# Generated by Django 2.1.5 on 2019-09-11 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20190906_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='color',
        ),
        migrations.AddField(
            model_name='maploads',
            name='last_load_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
