# Generated by Django 2.1.5 on 2019-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20190911_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maploads',
            name='last_load_at',
        ),
        migrations.AddField(
            model_name='maploads',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='maploads',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
