# Generated by Django 2.1.5 on 2019-10-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20190916_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_loads', to='organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_widget_loads', models.IntegerField(default=0)),
                ('max_page_loads', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='PageLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('widget_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_loads', to='organizations.WidgetLoad')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_loads', to='organizations.Organization')),
            ],
        ),
    ]
