# Generated by Django 2.1.5 on 2019-10-16 01:41

from django.db import migrations


def populate_org_widget(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OrganizationWidget = apps.get_model("organizations", "OrganizationWidget")

    for org in Organization.objects.filter(widget__isnull=True):
        OrganizationWidget.objects.create(organization=org)


class Migration(migrations.Migration):

    dependencies = [("organizations", "0011_add_map_load_and_page_load")]

    operations = [migrations.RunPython(populate_org_widget, migrations.RunPython.noop)]
