# Generated by Django 2.1.5 on 2019-10-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_populate_org_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maploads',
            name='organization',
        ),
        migrations.DeleteModel(
            name='MapLoads',
        ),
    ]
