# Generated by Django 2.0.4 on 2018-11-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_index_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
