# Generated by Django 2.0.4 on 2018-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_index_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='type',
            field=models.CharField(choices=[('trail', 'Trail'), ('municipality', 'Municipality'), ('mountain', 'Mountain'), ('region', 'Region'), ('network', 'Network'), ('location', 'Location')], max_length=16),
        ),
    ]
