# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
