# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 18:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='url',
        ),
    ]
