# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20160929_1919'),
        ('utils', '0002_remove_address_url'),
    ]

    operations = [
    ]
