# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 14:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_image_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExploitationPeriod',
        ),
    ]
