# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 17:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20170127_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningDates',
        ),
    ]
