# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 17:04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_delete_openingdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='photos/'),
        ),
    ]
