# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20170201_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(blank=True, default='photo', max_length=20, null=True),
        ),
    ]
