# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 17:28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20170317_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
