# Generated by Django 2.0.4 on 2018-11-23 00:55

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_auto_20170317_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=300, null=True, upload_to='photos/'),
        ),
    ]
