# Generated by Django 2.0.4 on 2018-11-23 01:41

from django.db import migrations


def migrate_images(apps, schema_editor):
    Trail = apps.get_model('hike', 'Trail')
    TrailImage = apps.get_model('hike', 'TrailImage')
    for t in Trail.objects.all():
        print('trail: {}'.format(t.trail_id))
        for i in t.images.all():
            if not i.image:
                continue
            print('  {}'.format(i.image))
            image_type = 'unknown'
            if i.image_type:
                image_type = i.image_type
            try:
                TrailImage.objects.get(trail=t, image=i.image)
            except TrailImage.DoesNotExist:
                TrailImage.objects.create(
                    trail=t,
                    image_type=image_type,
                    image=i.image,
                    credit=i.credit
                )

    Location = apps.get_model('location', 'Location')
    LocationImage = apps.get_model('location', 'LocationImage')
    for l in Location.objects.all():
        print('location: {}'.format(l.location_id))
        for i in l.images.all():
            if not i.image:
                continue
            print('  {}'.format(i.image))
            image_type = 'unknown'
            if i.image_type:
                image_type = i.image_type
            try:
                LocationImage.objects.get(location=l, image=i.image)
            except LocationImage.DoesNotExist:
                LocationImage.objects.create(
                    location=l,
                    image_type=image_type,
                    image=i.image,
                    credit=i.credit
                )

    PointOfInterest = apps.get_model('location', 'PointOfInterest')
    PointOfInterestImage = apps.get_model('location', 'PointOfInterestImage')
    for p in PointOfInterest.objects.all():
        print('poi: {}'.format(p.poi_id))
        for i in p.images.all():
            if not i.image:
                continue
            print('  {}'.format(i.image))
            image_type = 'unknown'
            if i.image_type:
                image_type = i.image_type
            try:
                PointOfInterestImage.objects.get(location=p, image=i.image)
            except PointOfInterestImage.DoesNotExist:
                PointOfInterestImage.objects.create(
                    location=p,
                    image_type=image_type,
                    image=i.image,
                    credit=i.credit
                )


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20181123_0055'),
        ('hike', '0052_trailimage'),
        ('location', '0027_locationimage_pointofinterestimage'),
    ]

    operations = [
        #
        # This migration is broken, so comment out this operation for now
        #
        # migrations.RunPython(migrate_images)
    ]
