# Generated by Django 2.1.5 on 2019-03-06 14:33

from django.db import migrations


def update_contact_type(apps, schema_editor):
    Contact = apps.get_model("utils", "Contact")

    types = [
        ("Blogue", "blog"),
        ("Cellulaire", "cellular"),
        ("Courriel", "email"),
        ("Facebook", "facebook"),
        ("Site Internet mobile", "site_mobile"),
        ("Site Internet", "site"),
        ("Twitter", "twitter"),
        ("Télécopieur", "fax"),
        ("Téléphone sans frais", "telephone_no_charge"),
        ("Téléphone secondaire", "telephone_secondary"),
        ("Téléphone", "telephone"),
    ]

    for old_type, new_type in types:
        Contact.objects.filter(type__iexact=old_type).update(type=new_type)


class Migration(migrations.Migration):

    dependencies = [("utils", "0012_delete_image")]

    operations = [migrations.RunPython(update_contact_type, migrations.RunPython.noop)]
